[produce]
carrots
yellow onion | sweet onion | onion
garlic
fresh dill
baby spinach
lemon
mushrooms
celery
kale
horseradish
ginger root
fresh turmeric
habanero chilis
fresh rosemary
fresh thyme
fresh parsley

[pantry & canned]
long-grain white rice
olive oil
chickpeas
tomato paste
vegetable broth
nutritional yeast
white miso
dry white wine
raw apple cider vinegar
raw honey

[spices & seasoning]
dried oregano
paprika
Italian herb seasoning
ground coriander
ground turmeric
red pepper flakes
salt
black pepper
black peppercorns
cinnamon stick
allspice berries
whole cloves

[dairy & alt-dairy]
plant milk
parmesan cheese
heavy cream
cheese tortellini
